name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
          activate-environment: myenv

      - name: install package and test
        shell: bash -l {0}
        run: |
          python setup.py install 
          pytest
          echo "Tests complete"

      - name: create sdist
        shell: bash -l {0}
        run: |
          python setup.py sdist

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.tar.gz