name: test-suite

# Only run this for pushes to master and for pull requests to master
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"] # dropping windows-latest from test matrix due to issues with rpy2 issue #73

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false
        activate-environment: myenv

    - name: install pytest-cov
      shell: bash -l {0}
      run: |
        pip install pytest-cov
    # run pytest within conda environment
    - name: Run pytest and generate coverage report
      shell: bash -l {0}
      run: |
        pytest --cov=walkers tests/ --cov-report=xml
    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml